from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 520)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ACG.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cmbCloud = QtWidgets.QComboBox(self.centralwidget)
        self.cmbCloud.setGeometry(QtCore.QRect(20, 130, 181, 22))
        self.cmbCloud.setObjectName("cmbCloud")
        self.lnAddress = QtWidgets.QLineEdit(self.centralwidget)
        self.lnAddress.setGeometry(QtCore.QRect(432, 130, 341, 20))
        self.lnAddress.setObjectName("lnAddress")
        self.lnPort = QtWidgets.QLineEdit(self.centralwidget)
        self.lnPort.setGeometry(QtCore.QRect(20, 230, 181, 20))
        self.lnPort.setObjectName("lnPort")
        self.lnServer = QtWidgets.QLineEdit(self.centralwidget)
        self.lnServer.setGeometry(QtCore.QRect(280, 230, 171, 20))
        self.lnServer.setObjectName("lnServer")
        self.cmbSSL = QtWidgets.QComboBox(self.centralwidget)
        self.cmbSSL.setGeometry(QtCore.QRect(530, 230, 151, 22))
        self.cmbSSL.setObjectName("cmbSSL")
        self.lnAddress_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lnAddress_2.setGeometry(QtCore.QRect(430, 330, 341, 20))
        self.lnAddress_2.setObjectName("lnAddress_2")
        self.lnAddress_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lnAddress_3.setGeometry(QtCore.QRect(20, 330, 341, 20))
        self.lnAddress_3.setObjectName("lnAddress_3")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(330, 400, 111, 41))
        self.btnSave.setObjectName("btnSave")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 100, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 100, 341, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 200, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 200, 171, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(530, 200, 151, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 300, 341, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 300, 341, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.cmbConfig = QtWidgets.QComboBox(self.centralwidget)
        self.cmbConfig.setGeometry(QtCore.QRect(290, 40, 181, 22))
        self.cmbConfig.setObjectName("cmbConfig")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(290, 10, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ACG Thread Manager - Setup Connection"))
        self.btnSave.setText(_translate("MainWindow", "Save Configuration"))
        self.label.setText(_translate("MainWindow", "IBM Cloud"))
        self.label_2.setText(_translate("MainWindow", "Address"))
        self.label_3.setText(_translate("MainWindow", "HTTP Port Number"))
        self.label_4.setText(_translate("MainWindow", "Instance Name"))
        self.label_5.setText(_translate("MainWindow", "Use SSL"))
        self.label_6.setText(_translate("MainWindow", "CAM Namespace ID"))
        self.label_7.setText(_translate("MainWindow", "SSO Gateway"))
        self.label_8.setText(_translate("MainWindow", "Choose Existing Configuration"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
